version: '2'
services:
  postgresql:
    image: postgres:15
    container_name: shop_automator_db
    #    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=somePassword
    network_mode: "bridge"
    ports:
      - "54321:5432"
